# Generated by Django 5.1 on 2024-09-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_attempted', models.IntegerField(default=0)),
                ('test_score', models.FloatField(default=0)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('que_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('que', models.TextField()),
                ('opt_1', models.CharField(max_length=255)),
                ('opt_2', models.CharField(max_length=255)),
                ('opt_3', models.CharField(max_length=255)),
                ('opt_4', models.CharField(max_length=255)),
                ('correct_ans', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('res_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_attempted', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('attempts', models.IntegerField()),
                ('right_attempts', models.IntegerField()),
                ('wrong_attempts', models.IntegerField()),
                ('test_score', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.candidate')),
            ],
        ),
    ]
