# Generated by Django 5.1 on 2024-09-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.exam'),
        ),
    ]
