# Generated by Django 5.1 on 2024-09-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_candidate_test_attempted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
