# Generated by Django 5.1 on 2024-09-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(default='1 month', max_length=255),
        ),
    ]
