# Generated by Django 5.1 on 2024-09-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_plans_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(default='Monthly Pass', max_length=255),
        ),
    ]
