# Generated by Django 5.1 on 2024-09-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_plans_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(default='Monthly Pass', max_length=255),
        ),
    ]
