# Generated by Django 5.1 on 2024-09-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_notes_alter_plans_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.ImageField(upload_to='images'),
        ),
    ]
