# Generated by Django 5.1 on 2024-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='validity',
            field=models.CharField(default='Valid for 30 Days', max_length=255),
        ),
    ]
