# Generated by Django 5.1 on 2024-10-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_plans_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.exam'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='que_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='res_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
